### ISSUE TITLE
Add interoperability with Gradle 2.7

### ISSUE THREAD

**Issue by szpak** [4finance/micro-common-release#19]
As reported by @marcingrzejszczak in https://github.com/4finance/micro-infra-spring/pull/501 micro-common-release is probably not compatible with Gradle 2.7.

**Comment by szpak** [comment]
@tkrzeminski Can it be closed not?

**Comment by tkrzeminski** [comment]
@szpak yes, gradle bumped in https://github.com/4finance/micro-infra-spring/pull/633
